### ISSUE TITLE
Missing starter for gatsby-corporate (404)

### ISSUE THREAD

**Issue by dennisameling** [strapi/starters-and-templates#29]
[`strapi-starter-gatsby-corporate`](https://github.com/strapi/strapi-starter-gatsby-corporate) mentions that it's deprecated and links to https://github.com/strapi/starters-and-templates/tree/main/packages/starters/gatsby-corporate, which doesn't exist (404).

Is someone already creating that starter, or can I help in any way?

**Comment by remidej** [comment]
Sorry about that! We do plan on migrating the Gatsby corporate starter. We added the link in the other repo already, because we're going to archive it and Github won't allow us to change the readme after that.

I think what we can do for now it create a folder with just a readme for now to explain the situtation

**Comment by dennisameling** [comment]
Sounds good - appreciate it, thanks! 😊
